const D=window.DRAUGHT_DATA;const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
$('#stats').innerHTML=[['Approved boards',D.boards.length],['Visible frames',D.boards.reduce((a,b)=>a+b.frame_count,0)],['Implementation states',D.states.length],['UX flows',D.flows.length]].map(([l,v])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join('');
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
const groups=[...new Set(D.boards.map(b=>b.group))].sort();groups.forEach(g=>$('#boardGroup').insertAdjacentHTML('beforeend',`<option>${esc(g)}</option>`));
const sections=[...new Set(D.states.map(s=>s.section))];sections.forEach(g=>$('#stateSection').insertAdjacentHTML('beforeend',`<option>${esc(g)}</option>`));
function renderBoards(){const q=$('#boardSearch').value.toLowerCase(),g=$('#boardGroup').value;const rows=D.boards.filter(b=>(!g||b.group===g)&&(!q||(b.title+' '+b.screens.join(' ')).toLowerCase().includes(q)));$('#boardGrid').innerHTML=rows.map(b=>`<article class="card"><img loading="lazy" src="../approved-visuals/${esc(b.filename)}" alt="${esc(b.title)}"><div class="card-body"><div class="meta"><span class="tag gold">${b.visual_id}</span><span class="tag">${esc(b.group)}</span><span class="tag">${b.frame_count} frames</span><span class="tag">${esc(b.role)}</span></div><h3>${esc(b.title)}</h3><p>${esc(b.status)}</p><button data-view="${b.visual_id}">View board & screen list</button></div></article>`).join('')||'<p>No matching boards.</p>';document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>openBoard(x.dataset.view))}
function openBoard(id){const b=D.boards.find(x=>x.visual_id===id);$('#viewerBody').innerHTML=`<h2>${esc(b.title)}</h2><p class="eyebrow">${esc(b.status)} · ${esc(b.role)}</p><img src="../approved-visuals/${esc(b.filename)}" alt="${esc(b.title)}"><h3>Frames on this board</h3><ul>${b.screens.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;$('#viewer').showModal()}
$('#closeViewer').onclick=()=>$('#viewer').close();$('#viewer').addEventListener('click',e=>{if(e.target===$('#viewer'))$('#viewer').close()});$('#boardSearch').oninput=renderBoards;$('#boardGroup').onchange=renderBoards;
function renderStates(){const q=$('#stateSearch').value.toLowerCase(),sec=$('#stateSection').value,vs=$('#visualStatus').value;const rows=D.states.filter(s=>(!sec||s.section===sec)&&(!vs||s.visual_status===vs)&&(!q||JSON.stringify(s).toLowerCase().includes(q)));$('#stateRows').innerHTML=rows.map(s=>`<tr><td><strong>${esc(s.screen_id)}</strong><small>Legacy ${s.legacy_state_no}</small></td><td>${esc(s.title)}<small>${esc(s.kind)} · ${esc(s.route_or_overlay)}</small></td><td>${esc(s.section)}</td><td>${esc(s.approved_visual_refs)}<small>${esc(s.visual_status)}</small></td><td>${esc(s.event||'—')}<small>${esc(s.endpoint||'—')}</small></td><td>${esc(s.authority)}</td></tr>`).join('')};['stateSearch','stateSection','visualStatus'].forEach(id=>$('#'+id).addEventListener(id==='stateSearch'?'input':'change',renderStates));
$('#flowGrid').innerHTML=D.flows.map(f=>`<article class="card"><img loading="lazy" src="../ux-flows/${esc(f.filename)}" alt="${esc(f.title)}"><div class="card-body"><div class="meta"><span class="tag gold">${f.id}</span></div><h3>${esc(f.title)}</h3><p>${esc(f.invariant)}</p></div></article>`).join('');renderBoards();renderStates();